### ISSUE TITLE
Introduction of OpenTick?

### ISSUE THREAD

**Issue by xumengpanda** [opentradesolutions/opentick#1]
Could you provide a description of what open tick can achieve? 
What are the features it provides on top of FoundationDB?

Thanks,

**Comment by open-trade** [comment]
https://www.v2ex.com/t/513282

**Comment by xumengpanda** [comment]
Thanks for sharing the article!
The articles says Tick implements a **subset** of CQL. Can you elaborate on which specific query Tick supports and which it does not support?

**Comment by open-trade** [comment]
type Ast struct {
	Select *AstSelect `"SELECT" @@`
	Insert *AstInsert `| "INSERT" @@`
	Create *AstCreate `| "CREATE" @@`
	Drop   *AstDrop   `| "DROP" @@`
	Delete *AstDelete `| "DELETE" @@`
}

type AstDrop struct {
	Table    *AstTableName `"TABLE" @@`
	Database *string       `| "DATABASE" @Ident`
}

type AstCreate struct {
	Table    *AstCreateTable    `"TABLE" @@`
	Database *AstCreateDatabase `| "DATABASE" @@`
}

type AstDelete struct {
	Table *AstTableName  `"FROM" @@`
	Where *AstExpression `["WHERE" @@]`
}

type AstCreateDatabase struct {
	IfNotExists *string `[@("IF" "NOT" "EXISTS")]`
	Name        *string `@Ident`
}

type AstCreateTable struct {
	IfNotExists *string       `[@("IF" "NOT" "EXISTS")]`
	Name        *AstTableName `@@`
	Cols        []AstTypeDef  `"(" @@ {"," @@} ")"`
}

type AstTypeDef struct {
	Key  []string `"PRIMARY" "KEY" "(" @Ident {"," @Ident} ")"`
	Name *string  `| @Ident`
	Type *string  `@{"BIGINT" | "TINYINT" | "SMALLINT" | "INT"  | "DOUBLE" | "FLOAT" | "TIMESTAMP" | "BOOLEAN" | "TEXT"}`
}

type AstInsert struct {
	Table  *AstTableName `"INTO" @@`
	Cols   []string      `"(" @Ident {"," @Ident} ")"`
	Values []AstValue    `"VALUES" "(" @@ {"," @@} ")"`
}
