### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by electricmomo** [opentradesolutions/opentick#2]
Hi,
I cannot build this project. I am getting the error below:

[momo@dev-linux-dreamer-1 opentick]$ make build
cd main; go build -o ../opentick main.go; cd -
main.go:5:2: cannot find package "github.com/opentradesolutions/opentick" in any of:
	/opt/go/src/github.com/opentradesolutions/opentick (from $GOROOT)
	/home/momo/goapps/src/github.com/opentradesolutions/opentick (from $GOPATH)
/home/momo/sourcecode/opentradessolutions/opentick
[momo@dev-linux-dreamer-1 opentick]$ 

I am using go version go1.10.1 linux/amd64 on Centos 7.6
Any idea to so,ve this?

Thanks

**Comment by open-trade** [comment]
You need to use Go >=1.11 which has module support
